services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tetris-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    container_name: tetris-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
